coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
  ignore:
    - 'packages/turbo-sdk/src/cli/*'
    - 'packages/turbo-sdk/src/cli/commands/*'
    - 'packages/turbo-sdk/src/common/token/*'
